Not Found: /api/v1.0/server/tuoguan
[pid: 15156|app: 0|req: 2997/4512] 127.0.0.1 () {34 vars in 764 bytes} [Sat May 11 19:32:07 2019] GET /api/v1.0/server/tuoguan => generated 3452 bytes in 4 msecs (HTTP/1.0 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /api/v1.0/server/job
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "./api/views.py", line 47, in get
    imgfile = os.path.join(settings.MEDIA_ROOT, md5)
  File "/usr/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'Sat May 11 19:32:17 2019 - logsize: 1502, triggering rotation to /home/ubuntu/plan/log/uwsgi-3389.log.1557574337...
