Not Found: /
[pid: 15156|app: 0|req: 2958/4449] 127.0.0.1 () {32 vars in 553 bytes} [Sat May 11 11:10:06 2019] GET / => generated 2019 bytes in 3 msecs (HTTP/1.0 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 15156|app: 0|req: 2959/4450] 127.0.0.1 () {26 vars in 373 bytes} [Sat May 11 11:11:34 2019] GET / => generated 2019 bytes in 3 msecs (HTTP/1.0 404) 3 headers in 102 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/wsgi.py", line 145, in __call__
    request = self.request_class(environ)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/wsgi.py", line 86, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 15156|app: 0|req: 2960/4451] 183.57.54.43 () {8 vars in 89 bytes} [Sat May 11 12:03:18 2019]   => generated 0 bytes in 32 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Not Found: /
[pid: 15158|app: 0|req: 951/4452] 183.57.54.43 () {18 vars in 183 bytes} [Sat May 11 12:03:18 2019] GET / => generated 2032 bytes in 4 msecs (HTTP/1.0 404) 3 headers in 102 bytes (1 switches on core 0)
Sat May 11 12:03:19 2019 - logsize: 1181, triggering rotation to /home/ubuntu/plan/log/uwsgi-3389.log.1557547399...
